name: Python autotests

on: 
  workflow_dispatch:
    inputs: 
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Укажите нужную вам версию Python

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Allure CLI
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-11-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
        tar -zxvf allure-2.24.1.tgz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate report
      run: |
        allure generate -c allure-results -o _site  # Генерация отчета Allure в директорию _site

    - name: Save allure report
      uses: actions/upload-artifact@v4  # Использование актуальной версии действия
      with:
        name: _site
        path: _site
        retention-days: 1

  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests  # Этот шаг выполняется после успешного завершения job run-tests

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: _site

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1.2.9
