name: Python autotests

on: 
  workflow_dispatch:
    inputs: 
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run smoke tests
      if: ${{ inputs.deployment_target == 'smoke' }}
      run: |
        . venv/bin/activate
        pytest --alluredir=allure-results -m smoke

    - name: Run regression tests
      if: ${{ inputs.deployment_target == 'regression' }}
      run: |
        . venv/bin/activate
        pytest --alluredir=allure-results -m regression

    - name: Run extended tests
      if: ${{ inputs.deployment_target == 'extended' }}
      run: |
        . venv/bin/activate
        pytest --alluredir=allure-results -m extended

    - name: Run all tests
      if: ${{ inputs.deployment_target == 'all' }}
      run: |
        . venv/bin/activate
        pytest --alluredir=allure-results

    - name: Generate Allure report
      run: |
        mkdir -p allure-report
        allure generate allure-results -o allure-report --clean

    - name: Publish Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report

    - name: Deploy Allure Report to GitHub Pages
      if: ${{ success() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
