name: Python autotests

on: 
  workflow_dispatch:
    inputs: 
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest > result.log  # Запуск тестов и сохранение вывода в файл result.log

    - name: Save test results
      uses: actions/upload-artifact@v4  # Обновлено до актуальной версии
      with:
        name: test-results
        path: result.log
        retention-days: 1

  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
    - name: Download test results
      uses: actions/download-artifact@v3  # Остаемся на v3, так как v4 еще не существует
      with:
        name: test-results

    - name: Prepare GitHub Pages content
      run: |
        mkdir -p _site
        mv result.log _site/index.html  # Перемещаем лог в папку _site и переименовываем в index.html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v4  # peaceiris поддерживает v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
